artifact_uri: file:///E:/customer_churn_prediction/reports/figures/813061646777885842/3534cab15a204eefb0e0593f6886ec3a/artifacts
end_time: 1755965185427
entry_point_name: ''
experiment_id: '813061646777885842'
lifecycle_stage: active
run_id: 3534cab15a204eefb0e0593f6886ec3a
run_name: random_forest_userlevel
source_name: ''
source_type: 4
source_version: ''
start_time: 1755965155260
status: 3
tags: []
user_id: Future
