name: CI - Code Quality
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run linters
        run: |
          pip install flake8
          flake8 src/ notebooks/
      - name: Run unit tests
        run: |
          pip install pytest
          pytest src/churn/tests/