name: Data Drift Monitor
on:
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  drift-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run drift check
        run: |
          python src/churn/utils.py --check-drift data/processed/train_user_feats.csv