name: Data & Schema Validation
on:
  push:
    paths:
      - 'data/raw/**'
      - 'src/churn/features.py'
jobs:
  validate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Validate schema
        run: |
          python src/churn/utils.py --validate-schema data/raw/train.csv