name: Model Quality Check
on:
  pull_request:
    branches: [main]
jobs:
  train-test-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run quick training & assert metrics
        run: |
          python src/churn/modeling/train.py --sample --assert-metrics