artifact_uri: file:///E:/customer_churn_prediction/reports/figures/813061646777885842/1aa3e559e6d344c2aa0a34ceee8be329/artifacts
end_time: 1755965974279
entry_point_name: ''
experiment_id: '813061646777885842'
lifecycle_stage: active
run_id: 1aa3e559e6d344c2aa0a34ceee8be329
run_name: xgb_optuna_recall_study
source_name: ''
source_type: 4
source_version: ''
start_time: 1755965860440
status: 3
tags: []
user_id: Future
