artifact_uri: file:///E:/customer_churn_prediction/reports/figures/813061646777885842/ef636a0dd7f54496af4686422f28baef/artifacts
end_time: 1755957212011
entry_point_name: ''
experiment_id: '813061646777885842'
lifecycle_stage: active
run_id: ef636a0dd7f54496af4686422f28baef
run_name: xgb_userlevel_final
source_name: ''
source_type: 4
source_version: ''
start_time: 1755957205864
status: 3
tags: []
user_id: Future
