artifact_uri: file:///E:/customer_churn_prediction/reports/figures/813061646777885842/c0d301dcef7341939efec211ae8a8b20/artifacts
end_time: 1755959165617
entry_point_name: ''
experiment_id: '813061646777885842'
lifecycle_stage: active
run_id: c0d301dcef7341939efec211ae8a8b20
run_name: xgb_userlevel_extended
source_name: ''
source_type: 4
source_version: ''
start_time: 1755959163536
status: 4
tags: []
user_id: Future
