artifact_uri: file:///E:/customer_churn_prediction/reports/figures/813061646777885842/40f850e0f02a4b5dab8f738bf0325dce/artifacts
end_time: 1755965678709
entry_point_name: ''
experiment_id: '813061646777885842'
lifecycle_stage: active
run_id: 40f850e0f02a4b5dab8f738bf0325dce
run_name: xgb_optuna_recall_study
source_name: ''
source_type: 4
source_version: ''
start_time: 1755965678620
status: 4
tags: []
user_id: Future
