artifact_uri: file:///E:/customer_churn_prediction/reports/figures/813061646777885842/68f428bcbb4d482880bb02efb2df99ac/artifacts
end_time: 1755965789387
entry_point_name: ''
experiment_id: '813061646777885842'
lifecycle_stage: active
run_id: 68f428bcbb4d482880bb02efb2df99ac
run_name: xgb_optuna_recall_study
source_name: ''
source_type: 4
source_version: ''
start_time: 1755965789317
status: 4
tags: []
user_id: Future
