artifact_uri: file:///E:/customer_churn_prediction/reports/figures/813061646777885842/680b2fcd4e544ba68eb0ca03d96e9a98/artifacts
end_time: 1755965191359
entry_point_name: ''
experiment_id: '813061646777885842'
lifecycle_stage: active
run_id: 680b2fcd4e544ba68eb0ca03d96e9a98
run_name: logistic_regression_userlevel
source_name: ''
source_type: 4
source_version: ''
start_time: 1755965185483
status: 3
tags: []
user_id: Future
