artifact_location: file:///E:/customer_churn_prediction/reports/figures/813061646777885842
creation_time: 1755957205633
experiment_id: '813061646777885842'
last_update_time: 1755957205633
lifecycle_stage: active
name: second_customer_churn_xgb_experiment
